---
title: "4ème Colloque R du CSBQ <br> 4th QCBS R Symposium"
subtitle:
author:
institute: "Québec Centre for Biodiversity Science <br>"
date: "<br> `r Sys.Date()`<br> <span class=footnote> Use arrow keys to navigate. Press `H` for help. </span>"
output:
  xaringan::moon_reader:
    css: ["default",  "css/phpb-fonts.css", "css/phpb-theme.css"]
    lib_dir: libs
    self-contained: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: true
      ratio: '16:9'
      beforeInit: ["macro.js", "https://platform.twitter.com/widgets.js"]
      navigation:
        scroll: false   # disable slide transitions by scrolling
    includes:
      in_header: header.html
---
class: bottom, inverse

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)

knitr::opts_chunk$set(
  collapse = TRUE,
  dev = 'jpeg',
  ffmpeg.format='gif',
  interval = 1/15
)


required.libraries <- c("ggplot2", "plotly", "RColorBrewer", # for visualisation
                        "devtools", "reticulate", "png", "knitr", "JuliaCall", "here"
)

needed.libraries <- required.libraries[!(required.libraries %in%
                                           installed.packages()[ ,"Package"])]

if(length(needed.libraries)) install.packages(needed.libraries)

# Load all required libraries at once
lapply(required.libraries, library, character.only = TRUE, quietly = TRUE)


# Include packages to be loaded below here:
library(knitr)    # For knitting document and include_graphics function
library(ggplot2)  # For plotting
library(JuliaCall)
library(reticulate)
library(ggplot2)
library(png)      # For grabbing the dimensions of png files
```


We begin our symposium by acknowledging that Concordia University is located on unceded Indigenous lands.

The Kanien’kehá:ka Nation is recognized as the custodians of the lands and waters on which we gather today.

Tiohtià:ke (Montréal) is historically known as a gathering place for many First Nations.

The institutions from which this symposium participants and presenters belong to and that are associated with the Québec Centre for Biodiversity Science are also located in unceded Indigenous territories, including those from the W8banaki, the Abénaki, and the Huron-Wendat Nations.

Today, these regions are home to diverse populations of Indigenous and other peoples.

We respect the continued connections with the past, present and future in our ongoing relationships with Indigenous and other peoples within the Montreal community.

???



---
# QCBS R Symposia

QCBS R Symposium provides an opportunity for teaching and participation in a series of contributed R workshops about the application of biodiversity science analyses using R that are not offered during the annual QCBS R Workshop Series.

.pull-left[
.pull-left[

1st QCBS Symposium
Gault-Nature Reserve McGill


]
]

